FROM php:8.4-fpm

RUN apt-get update && apt-get install -y \
    libpng-dev \
	libonig-dev \
    libjpeg-dev \
    libwebp-dev \
    libfreetype6-dev \
    supervisor \
    unzip \
    curl \
    && docker-php-ext-configure gd \
        --with-jpeg \
        --with-webp \
        --with-freetype \
    && docker-php-ext-install \
        gd \
        pdo \
        pdo_mysql \
        mbstring \
        exif \
        opcache \
    && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/chat

COPY supervisord.docker.conf /etc/supervisor/conf.d/supervisord.conf

RUN mkdir -p /var/log/supervisor

EXPOSE 9000 8080

CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf"]
